#ifndef HUBBARD_HEAD_VERSION_HPP
#define HUBBARD_HEAD_VERSION_HPP


// Define all the version numbers
#define HUBBARD_HEAD_MAJOR_VERSION (0)
#define HUBBARD_HEAD_MINOR_VERSION (0)
#define HUBBARD_HEAD_PATCH_VERSION (1)
#define HUBBARD_HEAD_VERSION "0.0.1"


#endif // HUBBARD_HEAD_VERSION_HPP
